version: "3"
services:
    database:
        image: "postgres:10.5"
        container_name: "doctor-labelling-database"
        ports:
            - "5432:5432"
        volumes:
            - ./db-init/initialize-databases.sql:/docker-entrypoint-initdb.d/init.sql


